name: Build and Push Custom Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build ThingsBoard with Docker
      run: mvn clean install -DskipTests -Ddockerfile.skip=false
      env:
        MAVEN_OPTS: "-Xmx6g -XX:MaxMetaspaceSize=512m -XX:+UseG1GC"

    - name: Show built Docker images
      run: docker images

    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag and Push tb-node image
      run: |
        # Tag the main tb-node image (adjust if logs show different name/tag)
        docker tag thingsboard/tb-node:latest ghcr.io/takumiadmin/tb-node:latest
        docker tag thingsboard/tb-node:latest ghcr.io/takumiadmin/tb-node:${GITHUB_SHA::7}
        docker push ghcr.io/takumiadmin/tb-node:latest
        docker push ghcr.io/takumiadmin/tb-node:${GITHUB_SHA::7}
